spring:
  mail:
    host: smtp.qq.com
    username: 878690773@qq.com
    password: cenvrrixvmhdbfia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true